article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    path('', views.index, name='index'),
    path('learn/', views.learn, name='learn'),
    path('about/', views.about, name='about'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='article')),
    path('', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register')
]

article/models.py
from django.db import models
from django.utils.timezone import now, localtime


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=254)
    # author = models.ForeignKey('User', on_delete=models.SET_NULL)
    create_time = models.DateTimeField(auto_now_add=now)
    modify_time = models.DateTimeField(auto_now=now)
    tags = models.ManyToManyField('Tag')
    content = models.TextField()
    removed = models.BooleanField()
    # comment = models.ForeignKey('Comment', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'article'
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tags'
        verbose_name = '标签'
        verbose_name_plural = verbose_name


# 评论
# class Comment(models.Model):
#     id = models.AutoField(primary_key=True)
#     comment = models.TextField()
#
#     class Meta:
#         db_table = 'comments'
#         verbose_name = '评论'
#         verbose_name_plural = verbose_name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManage(BaseUserManager):
    def _create_user(self, telephone, username, password, **kwargs):
        if not telephone:
            raise ValueError('必须要传递手机号')
        if not password:
            raise ValueError('必须要输入密码')
        user = self.model(telephone=telephone, username=username, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, telephone, username, password, id_superuser=False, **kwargs):
        kwargs['is_superuser'] = id_superuser
        return self._create_user(telephone=telephone, username=username, password=password, **kwargs)


class User(AbstractUser):
    telephone = models.CharField(max_length=11, unique=True)
    profession = models.CharField(max_length=100)

    USERNAME_FIELD = 'telephone'
    objects = UserManage()

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

article/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'article/index.html')


def learn(request):
    return render(request, 'article/list.html')


def about(request):
    return render(request, 'article/about.html')


def guestbook(request):
    return render(request, 'article/gbook.html')

users/views.py
from django.shortcuts import render
from .models import User
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse


def login_view(request):
    if request.method == 'GET':
        return render(request, 'users/login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if not username or not password:
            messages.error(request, '用户名或密码不能为空！')
            return render(request, 'users/login.html')
        user = authenticate(request, username=username, password=password)
        print(user)
        if user and user.is_active:
            # login(request, user)
            messages.success(request, '登录成功')
            print('登录成功')
            return render(request, 'article/index.html')
        else:
            messages.error(request, '用户名或密码错误')
            print('用户名或密码错误')
            return render(request, 'users/login.html')

def register_view(request):
    username = '12345'
    password = '54321'
    telephone = '12345678912'
    user = User.objects.create_user(telephone=telephone, username=username, password=password)
    print(user.username)
    return HttpResponse('successful')

templates/article/about.html
{% extends 'article/base.html' %}
{% load static %}

{% block article_list %}
    <h1 class="t_nav"><span>像“草根”一样，紧贴着地面，低调的存在，冬去春来，枯荣无恙。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">关于我</a>
    </h1>
    <div class="ab_box">
        <div class="leftbox">
            <div class="newsview">
                <div class="news_infos">
                    <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br/>
                        <br/>
                        SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br/>
                        <br/>
                        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br/>
                        <br/>
                        现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br/>
                        <br/>
                        自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp;
                        280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群
                        。我的个人微信号 yangqq_1987）</p>
                    <br/>
                    <h2>About my blog</h2>
                    &nbsp;
                    <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
                    <br/>
                    <p>服务器：阿里云服务器&nbsp;&nbsp;<a
                            href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm"
                            target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a>
                    </p>
                    <br/>
                    <p>备案号：蜀ICP备11002373号-1</p>
                    <br/>
                    <p>程 序：PHP 帝国CMS7.5</p>
                </div>
            </div>
        </div>
        <div class="rightbox">
            <div class="aboutme">
                <h2 class="hometitle">关于我</h2>
                <div class="avatar"><img src="{% static 'images/avatar.jpg' %}"></div>
                <div class="ab_con">
                    <p>网名：dancesmile | 杨青</p>
                    <p>职业：Web前端设计师、网页设计 </p>
                    <p>个人微信：yangqq_1987</p>
                    <p>邮箱：dancesmiling@qq.com</p>
                </div>
            </div>
            <div class="weixin">
                <h2 class="hometitle">微信关注</h2>
                <ul>
                    <img src="{% static 'images/wx.jpg' %}">
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>首页_我的个人博客</title>
    <meta name="keywords" content="个人博客,python博客,杨松柏"/>
    <meta name="description" content="杨松柏个人博客，是一个站在web前端设计之路的程序员个人网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/m.css' %}" rel="stylesheet">
    {% block style %}
        <!--css、js文件-->
    {% endblock %}

    <!--[if lt IE 9]>
    <script src="{% static 'js/modernizr.js' %}"></script>
    <![endif]-->
    <script>
        window.onload = function () {
            var oH2 = document.getElementsByTagName("h2")[0];
            var oUl = document.getElementsByTagName("ul")[0];
            oH2.onclick = function () {
                var style = oUl.style;
                style.display = style.display == "block" ? "none" : "block";
                oH2.className = style.display == "block" ? "open" : ""
            }
        }
    </script>
</head>
<body>
<header>
    <div class="tophead">
        <div class="logo"><a href="/">杨松柏个人博客</a></div>
        <div id="mnav">
            <h2><span class="navicon"></span></h2>
            <ul>
                <li><a href="/">网站首页</a></li>
                <li><a href="{% url 'article:about' %}">关于我</a></li>
                <li><a href="share.html">心情随笔</a></li>
                <li><a href="{% url 'article:learn' %}">学无止境</a></li>
                <li><a href="info.html">个人归档</a></li>
                <li><a href="gbook.html">留言</a></li>
                <li><a href="{% url 'users:login' %}">登录</a></li>
            </ul>
        </div>
        <nav class="topnav" id="topnav">
            <ul>
                <li><a href="/">网站首页</a></li>
                <li><a href="{% url 'article:about' %}">关于我</a></li>
                <li><a href="share.html">心情随笔</a></li>
                <li><a href="{% url 'article:learn' %}">学无止境</a></li>
                <li><a href="info.html">个人归档</a></li>
                <li><a href="gbook.html">留言</a></li>
                <li><a href="{% url 'users:login' %}">登录</a></li>
            </ul>
        </nav>
    </div>
</header>

{% block picshow %}
    <!--图片展示-->
{% endblock %}

<article>
    {% block article_list %}
        <!--博客列表-->
    {% endblock %}

    {% block sidebar %}
{#        <div class="sidebar">#}
{#            {% include 'include/about.html' %}#}
{##}
{#            {% include 'include/search.html' %}#}
{##}
{#            {% include 'include/cloud.html' %}#}
{##}
{#            {% include 'include/paihang.html' %}#}
{##}
{#            {% include 'include/tuijian.html' %}#}
{##}
{#            {% include 'include/links.html' %}#}
{##}
{#            {% include 'include/weixin.html' %}#}
{#        </div>#}
    {% endblock %}

</article>
<div class="blank"></div>
<footer>
    <p>Design by <a href="/">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<script src="{% static 'js/nav.js' %}"></script>
</body>
</html>

templates/article/gbook.html
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>留言_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="css/base.css" rel="stylesheet">
<link href="css/index.css" rel="stylesheet">
<link href="css/m.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script>
window.onload = function ()
{
	var oH2 = document.getElementsByTagName("h2")[0];
	var oUl = document.getElementsByTagName("ul")[0];
	oH2.onclick = function ()
	{
		var style = oUl.style;
		style.display = style.display == "block" ? "none" : "block";
		oH2.className = style.display == "block" ? "open" : ""
	}
}
</script>
</head>
<body>
<header>
  <div class="tophead">
    <div class="logo"><a href="/">杨青个人博客</a></div>
    <div id="mnav">
      <h2><span class="navicon"></span></h2>
      <ul>
        <li><a href="index.html">网站首页</a></li>
        <li><a href="about.html">关于我</a></li>
        <li><a href="share.html">模板分享</a></li>
        <li><a href="list.html">学无止境</a></li>
        <li><a href="info.html">慢生活</a></li>
        <li><a href="gbook.html">留言</a></li>
      </ul>
    </div>
    <nav class="topnav" id="topnav">
      <ul>
        <li><a href="index.html">网站首页</a></li>
        <li><a href="about.html">关于我</a></li>
        <li><a href="share.html">模板分享</a></li>
        <li><a href="list.html">学无止境</a></li>
        <li><a href="info.html">慢生活</a></li>
        <li><a href="gbook.html">留言</a></li>
      </ul>
    </nav>
  </div>
</header>
<article>
  <h1 class="t_nav"><span>像“草根”一样，紧贴着地面，低调的存在，冬去春来，枯荣无恙。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">留言</a></h1>
  <div class="ab_box">
    <div class="leftbox">
      <div class="newsview">
        <div class="news_infos"> 此处安装插件 </div>
      </div>
    </div>
    <div class="rightbox">
      <div class="aboutme">
        <h2 class="hometitle">关于我</h2>
        <div class="avatar"> <img src="images/avatar.jpg"> </div>
        <div class="ab_con">
          <p>网名：dancesmile | 杨青</p>
          <p>职业：Web前端设计师、网页设计 </p>
          <p>个人微信：yangqq_1987</p>
          <p>邮箱：dancesmiling@qq.com</p>
        </div>
      </div>
      <div class="weixin">
        <h2 class="hometitle">微信关注</h2>
        <ul>
          <img src="images/wx.jpg">
        </ul>
      </div>
    </div>
  </div>
</article>
<footer>
  <p>Design by <a href="/">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<script src="js/nav.js"></script>
</body>
</html>

templates/article/index.html
{% extends 'article/base.html' %}

<!--图片展示-->
{% block picshow %}
    <div class="picshow">
        <ul>
            <li><a href="/"><i><img src="{% static 'images/b01.jpg' %}"></i>
                <div class="font">
                    <h3>个人博客模板《早安》</h3>
                </div>
            </a></li>
            <li><a href="/"><i><img src="{% static 'images/b02.jpg' %}"></i>
                <div class="font">
                    <h3>个人博客模板《早安》</h3>
                </div>
            </a></li>
            <li><a href="/"><i><img src="{% static 'images/b03.jpg' %}"></i>
                <div class="font">
                    <h3>个人博客模板《早安》</h3>
                </div>
            </a></li>
            <li><a href="/"><i><img src="{% static 'images/b04.jpg' %}"></i>
                <div class="font">
                    <h3>个人博客模板《早安》</h3>
                </div>
            </a></li>
            <li><a href="/"><i><img src="{% static 'images/b05.jpg' %}"></i>
                <div class="font">
                    <h3>个人博客模板《早安》</h3>
                </div>
            </a></li>
        </ul>
    </div>
{% endblock %}

<!--博客列表-->
{% block article_list %}
    <div class="blogs">
        <li><span class="blogpic"><a href="/"><img src="{% static 'images/text02.jpg' %}"></a></span>
            <h3 class="blogtitle"><a href="/">陌上花开，可缓缓归矣</a></h3>
            <div class="bloginfo">
                <p>用最简单的代码，实现瀑布流布局，没有繁琐的css，没有jq，只需要做到以下就可以实现瀑布流的效果。思路很简单，看成是三列布局，分别用三个ul来调用。帝国cms列表模板，...</p>
            </div>
            <div class="autor"><span class="lm"><a href="/" title="CSS3|Html5" target="_blank"
                                                   class="classname">CSS3|Html5</a></span><span
                    class="dtime">2018-05-04</span><span class="viewnum">浏览（<a href="/">0</a>）</span><span
                    class="readmore"><a href="/">阅读原文</a></span></div>
        </li>
        <li><span class="blogpic"><a href="/"><img src="{% static 'images/text01.jpg' %}"></a></span>
            <h3 class="blogtitle"><a href="/">网页中图片属性固定宽度，如何用js改变大小</a></h3>
            <div class="bloginfo">
                <p>用最简单的代码，实现瀑布流布局，没有繁琐的css，没有jq，只需要做到以下就可以实现瀑布流的效果。思路很简单，看成是三列布局，分别用三个ul来调用。帝国cms列表模板，...</p>
            </div>
            <div class="autor"><span class="lm"><a href="/" title="CSS3|Html5" target="_blank"
                                                   class="classname">CSS3|Html5</a></span><span
                    class="dtime">2018-05-04</span><span class="viewnum">浏览（<a href="/">0</a>）</span><span
                    class="readmore"><a href="/">阅读原文</a></span></div>
        </li>
    </div>
{% endblock %}

templates/article/list.html
{% extends 'article/base.html' %}
{% load static %}

{% block article_list %}
    <h1 class="t_nav"><span>不要轻易放弃。学习成长的路上，我们长路漫漫，只因学无止境。 </span><a href="/" class="n1">网站首页</a><a href="/" class="n2">学无止境</a>
    </h1>
    <div class="blogs">
        <div class="mt20"></div>
        <li><span class="blogpic"><a href="/"><img src="{% static 'images/text02.jpg' %}"></a></span>
            <h3 class="blogtitle"><a href="/">陌上花开，可缓缓归矣</a></h3>
            <div class="bloginfo">
                <p>用最简单的代码，实现瀑布流布局，没有繁琐的css，没有jq，只需要做到以下就可以实现瀑布流的效果。思路很简单，看成是三列布局，分别用三个ul来调用。帝国cms列表模板，...</p>
            </div>
            <div class="autor"><span class="lm"><a href="/" title="CSS3|Html5" target="_blank" class="classname">CSS3|Html5</a></span><span
                    class="dtime">2018-05-04</span><span class="viewnum">浏览（<a href="/">0</a>）</span><span
                    class="readmore"><a href="/">阅读原文</a></span></div>
        </li>

        <div class="pagelist">
            <a title="Total record">&nbsp;<b>45</b> </a>
            <b>1</b>&nbsp;
            <a href="#">2</a>
            <a href="#">下一页</a>
            <a href="#">尾页</a>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    <div class="sidebar">
        {% include 'include/search.html' %}
        {% include 'include/lmnav.html' %}
        {% include 'include/cloud.html' %}
        {% include 'include/paihang.html' %}
        {% include 'include/tuijian.html' %}
        {% include 'include/weixin.html' %}
    </div>
{% endblock %}

templates/include/about.html
<div class="about">
    <div class="avatar"><img src="{% static 'images/avatar.jpg' %}" alt=""></div>
    <p class="abname">dancesmile | songbai</p>
    <p class="abposition">Web前端设计师、网页设计</p>
    <div class="abtext"> 一个90后草根站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验。</div>
</div>

templates/include/cloud.html
<div class="cloud">
    <h2 class="hometitle">标签云</h2>
    <ul>
        <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a
            href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a
            href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
    </ul>
</div>

templates/include/links.html
<div class="links">
    <h2 class="hometitle">友情链接</h2>
    <ul>
        <li><a href="http://www.yangqq.com" title="杨青个人博客">杨青个人博客</a></li>
        <li><a href="http://www.yangqq.com" title="杨青个人博客">杨青个人博客</a></li>
        <li><a href="http://www.yangqq.com" title="杨青个人博客">杨青个人博客</a></li>
    </ul>
</div>

templates/include/lmnav.html
<div class="lmnav">
    <h2 class="hometitle">栏目导航</h2>
    <ul class="navbor">
        <li><a href="#">关于我</a></li>
        <li><a href="share.html">心情随笔</a>
            <ul>
                <li><a href="list.html">个人博客模板</a></li>
                <li><a href="#">HTML5模板</a></li>
            </ul>
        </li>
        <li><a href="list.html">学无止境</a>
            <ul>
                <li><a href="list.html">学习笔记</a></li>
                <li><a href="#">HTML5+CSS3</a></li>
                <li><a href="#">网站建设</a></li>
            </ul>
        </li>
        <li><a href="#">个人归档</a></li>
    </ul>
</div>

templates/include/paihang.html
<div class="paihang">
    <h2 class="hometitle">点击排行</h2>
    <ul>
        <li><b><a href="/download/div/2015-04-10/746.html" target="_blank">【活动作品】柠檬绿兔小白个人博客模板30...</a></b>
            <p><i><img src="images/t02.jpg"></i>展示的是首页html，博客页面布局格式简单，没有复杂的背景，色彩局部点缀，动态的幻灯片展示，切换卡，标...</p>
        </li>
    </ul>
</div>

templates/include/search.html
<div class="search">
    <form action="#" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字"
               style="color: rgb(153, 153, 153);"
               onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}"
               onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
    </form>
</div>

templates/include/tuijian.html
<div class="paihang">
    <h2 class="hometitle">站长推荐</h2>
    <ul>
        <li><b><a href="/download/div/2015-04-10/746.html" target="_blank">【活动作品】柠檬绿兔小白个人博客模板30...</a></b>
            <p><i><img src="images/t02.jpg"></i>展示的是首页html，博客页面布局格式简单，没有复杂的背景，色彩局部点缀，动态的幻灯片展示，切换卡，标...</p>
        </li>
    </ul>
</div>

templates/include/weixin.html
<div class="weixin">
    <h2 class="hometitle">官方微信</h2>
    <ul>
        <img src="{% static 'images/wx.jpg' %}">
    </ul>
</div>

templates/users/login.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>首页_我的个人博客</title>
    <meta name="keywords" content="个人博客,python博客,杨松柏"/>
    <meta name="description" content="杨松柏个人博客，是一个站在web前端设计之路的程序员个人网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href="{% static 'users/css/style.css' %}" rel='stylesheet' type='text/css'/>

    <script>
        window.onload = function () {
            var oH2 = document.getElementsByTagName("h2")[0];
            var oUl = document.getElementsByTagName("ul")[0];
            oH2.onclick = function () {
                var style = oUl.style;
                style.display = style.display == "block" ? "none" : "block";
                oH2.className = style.display == "block" ? "open" : ""
            }
        }
    </script>
</head>
<body>
<header>
    <div class="tophead">
        <div class="logo"><a href="/">杨松柏个人博客</a></div>
        <div id="mnav">
            <h2><span class="navicon"></span></h2>
            <ul>
                <li><a href="/">网站首页</a></li>
                <li><a href="{% url 'article:about' %}">关于我</a></li>
                <li><a href="../article/share.html">心情随笔</a></li>
                <li><a href="{% url 'article:learn' %}">学无止境</a></li>
                <li><a href="../article/info.html">个人归档</a></li>
                <li><a href="../article/gbook.html">留言</a></li>
                <li><a href="{% url 'users:login' %}">登录</a></li>
            </ul>
        </div>
        <nav class="topnav" id="topnav">
            <ul>
                <li><a href="/">网站首页</a></li>
                <li><a href="{% url 'article:about' %}">关于我</a></li>
                <li><a href="../article/share.html">心情随笔</a></li>
                <li><a href="{% url 'article:learn' %}">学无止境</a></li>
                <li><a href="../article/info.html">个人归档</a></li>
                <li><a href="../article/gbook.html">留言</a></li>
                <li><a href="{% url 'users:login' %}">登录</a></li>
            </ul>
        </nav>
    </div>
</header>

{% block picshow %}
    <!--图片展示-->
{% endblock %}

<article>
    <script>
        $(document).ready(function (c) {
            $('.close').on('click', function (c) {
                $('.login-form').fadeOut('slow', function (c) {
                    $('.login-form').remove();
                });
            });
        });
    </script>
    <!--SIGN UP-->
    <h1>klasikal Login Form</h1>
    <div class="login-form">
        <div class="close"></div>
        <div class="head-info">
            <label class="lbl-1"> </label>
            <label class="lbl-2"> </label>
            <label class="lbl-3"> </label>
        </div>
        <div class="clear"></div>
        <div class="avtar">
            <img src="{% static 'users/images/avtar.png' %}"/>
        </div>
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" class="text" value="username" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}">
            <div class="key">
                <input type="password" name="password" value="password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}">
            </div>
            <div class="signin">
                <input type="submit" value="Login">
            </div>
        </form>
    </div>

</article>
<div class="blank"></div>
<footer>
    {#    <p>Design by <a href="/">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>#}
</footer>
<script src="{% static 'js/nav.js' %}"></script>
</body>
</html>